services:
  db:
    image: mariadb:11.3
    restart: unless-stopped
    networks:
      - default
    ports:
      - "3312:3306"
    environment:
      TZ: "Europe/Berlin"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: quadranto
      MYSQL_USER: quadranto
      MYSQL_PASSWORD: quadranto
