services:
  db:
    image: postgres:16
    restart: unless-stopped
    networks:
      - default
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: quadranto
      POSTGRES_PASSWORD: quadranto
      POSTGRES_DB: quadranto

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080